coverage:
  precision: 2
  round: down
  range: "80..90"
  status:
    project:
      default:
          target: auto
          threshold: 1%
          base: auto
    patch:
      default:
          target: 91%
          threshold: 1%
          base: auto
